# Generated by Django 5.1.4 on 2025-02-05 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre o Razón Social')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]{1}$')], verbose_name='RUT')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de Fantasía')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre de Contacto')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe estar en formato +56XXXXXXXXX', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono Principal')),
                ('alternative_phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono Alternativo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Principal')),
                ('alternative_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Alternativo')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
    ]
