# Generated by Django 5.1.2 on 2024-11-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('debit_commission_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Comisión Débito (%)')),
                ('credit_commission_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Comisión Crédito (%)')),
                ('credit_installments', models.IntegerField(verbose_name='Número de cuotas')),
                ('commission_includes_tax', models.BooleanField(default=True, verbose_name='Comisión incluye IVA')),
                ('deposit_delay_days', models.IntegerField(verbose_name='Días para depósito')),
                ('machine_rental', models.BooleanField(default=False, verbose_name='Arriendo de máquina')),
                ('machine_rental_cost', models.IntegerField(blank=True, null=True, verbose_name='Costo arriendo mensual')),
                ('electronic_billing', models.BooleanField(default=False, verbose_name='Emisión boletas electrónicas')),
                ('electronic_billing_cost', models.IntegerField(blank=True, null=True, verbose_name='Costo mensual boletas')),
            ],
            options={
                'verbose_name': 'Proveedor de Medios de Pago',
                'verbose_name_plural': 'Proveedores de Medios de Pago',
            },
        ),
    ]
