# Generated by Django 5.1.2 on 2024-11-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentprovider',
            name='credit_installments',
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Proveedor por defecto'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='max_installments',
            field=models.IntegerField(blank=True, help_text='Número máximo de cuotas permitidas', null=True, verbose_name='Máximo de cuotas'),
        ),
    ]
