# Generated by Django 5.1.4 on 2025-02-07 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_productstock_changes_detail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('date_started', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_progress', 'En Proceso'), ('pending_review', 'Pendiente de Revisión'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='products.category', verbose_name='Categorías')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Conteo de Inventario',
                'verbose_name_plural': 'Conteos de Inventario',
                'ordering': ['-date_started'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diferencia de cantidad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del ajuste')),
                ('justification', models.TextField(verbose_name='Justificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory_management.inventorycount')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad esperada')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad real')),
                ('last_counted_at', models.DateTimeField(blank=True, null=True, verbose_name='Último conteo')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_counts', to=settings.AUTH_USER_MODEL, verbose_name='Contado por')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory_management.inventorycount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Detalle de Conteo',
                'verbose_name_plural': 'Detalles de Conteo',
                'unique_together': {('inventory_count', 'product')},
            },
        ),
    ]
