# Generated by Django 5.1.4 on 2025-02-13 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycountdetail',
            name='previous_counts',
            field=models.JSONField(blank=True, default=dict, verbose_name='Conteos anteriores'),
        ),
        migrations.AddField(
            model_name='inventorycountdetail',
            name='recount_count',
            field=models.IntegerField(default=0, verbose_name='Número de reconteos'),
        ),
        migrations.AddField(
            model_name='inventorycountdetail',
            name='recount_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de reconteo'),
        ),
        migrations.AddField(
            model_name='inventorycountdetail',
            name='recount_requested',
            field=models.BooleanField(default=False, verbose_name='Reconteo solicitado'),
        ),
        migrations.AddField(
            model_name='inventorycountdetail',
            name='recount_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recount_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
    ]
