# Generated by Django 5.1.4 on 2025-02-14 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_inventorycountdetail_previous_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='applied',
            field=models.BooleanField(default=False, verbose_name='Ajuste aplicado'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='inventory_count_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory_management.inventorycountdetail', verbose_name='Detalle de inventario origen'),
        ),
    ]
