# Generated by Django 5.1.4 on 2025-02-15 21:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('PERSON', 'Persona Natural'), ('COMPANY', 'Empresa')], max_length=10, verbose_name='Tipo de Cliente')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='RUT debe tener formato XX.XXX.XXX-X', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]{1}$')], verbose_name='RUT')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Región')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Empresa')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cliente Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['rut'],
            },
        ),
    ]
