# Generated by Django 5.1.4 on 2025-02-16 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0015_productstock_reference_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=100, unique=True)),
                ('theme_color', models.CharField(max_length=7)),
                ('logo', models.ImageField(upload_to='catalogs/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_settings', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Catálogo',
                'verbose_name_plural': 'Configuraciones de Catálogo',
                'indexes': [models.Index(fields=['subdomain'], name='catalog_cat_subdoma_9518ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='CatalogFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'indexes': [models.Index(fields=['session_id', 'added_at'], name='catalog_cat_session_98ce34_idx')],
                'unique_together': {('session_id', 'product')},
            },
        ),
    ]
