# Generated by Django 5.1.4 on 2025-02-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='catalogconfig',
            name='catalog_cat_subdoma_9518ae_idx',
        ),
        migrations.AddField(
            model_name='catalogconfig',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogconfig',
            name='public_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='catalogconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='catalogconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='catalogs/'),
        ),
        migrations.AlterField(
            model_name='catalogconfig',
            name='theme_color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
    ]
