# Generated by Django 5.1.4 on 2025-02-17 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_catalogconfig_catalog_cat_subdoma_9518ae_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 17, 1, 10, 33, 634591, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
