# Generated by Django 5.1.2 on 2024-11-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_is_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(help_text='Fecha y hora de la venta. Si no se especifica, se usará la fecha actual.', verbose_name='Fecha y hora'),
        ),
    ]
