# Generated by Django 5.1.2 on 2024-11-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_bulk_sale_price_product_bulk_stock_and_more'),
        ('sales', '0005_alter_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='saledetail',
            name='is_bulk',
            field=models.BooleanField(default=False, help_text='Indica si es una venta a granel', verbose_name='Venta a granel'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad vendida (en sacos o kilos)', max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='unit_price',
            field=models.IntegerField(help_text='Precio por unidad o por kilo en caso de granel', verbose_name='Precio unitario'),
        ),
        migrations.CreateModel(
            name='SaleStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Cantidad tomada de este lote', max_digits=10, verbose_name='Cantidad')),
                ('sale_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saledetail', verbose_name='Detalle de venta')),
                ('stock_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstock', verbose_name='Movimiento de stock')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock en Venta',
                'verbose_name_plural': 'Movimientos de Stock en Ventas',
            },
        ),
        migrations.AddField(
            model_name='saledetail',
            name='stock_movements',
            field=models.ManyToManyField(related_name='sale_details', through='sales.SaleStockMovement', to='products.productstock', verbose_name='Movimientos de stock'),
        ),
    ]
