# Generated by Django 5.1.2 on 2024-11-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_bulk_sale_price_product_bulk_stock_and_more'),
        ('sales', '0006_remove_saledetail_purchase_price_saledetail_is_bulk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de compra del producto en el momento de la venta', max_digits=10, verbose_name='Precio de compra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto'),
        ),
    ]
