# Generated by Django 5.1.2 on 2024-11-22 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_saledetail_purchase_price_alter_saledetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='iva_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA a Pagar'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='iva_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA Crédito'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='iva_debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA Débito'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la venta. Si no se especifica, se usará la fecha actual.', verbose_name='Fecha y hora'),
        ),
    ]
