# Generated by Django 5.1.2 on 2024-11-22 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_providers', '0001_initial'),
        ('sales', '0008_saledetail_iva_a_pagar_saledetail_iva_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission_amount',
            field=models.IntegerField(default=0, verbose_name='Monto comisión'),
        ),
        migrations.AddField(
            model_name='sale',
            name='commission_tax',
            field=models.IntegerField(default=0, verbose_name='IVA comisión'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_providers.paymentprovider', verbose_name='Proveedor medio de pago'),
        ),
    ]
