# Generated by Django 5.1.2 on 2024-11-23 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_providers', '0002_remove_paymentprovider_credit_installments_and_more'),
        ('sales', '0009_sale_commission_amount_sale_commission_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='installments',
            field=models.IntegerField(blank=True, help_text='Número de cuotas para pagos con tarjeta de crédito', null=True, verbose_name='Número de cuotas'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_providers.paymentprovider', verbose_name='Proveedor de pago'),
        ),
    ]
