# Generated by Django 5.1.2 on 2024-11-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_installments_alter_sale_payment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='provider_installments',
            field=models.IntegerField(blank=True, help_text='Número de cuotas en que el proveedor realizará el pago', null=True, verbose_name='Cuotas a recibir'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='installments',
            field=models.IntegerField(blank=True, choices=[(0, 'Sin cuotas (Pago único)'), (3, '3 cuotas'), (6, '6 cuotas'), (12, '12 cuotas')], null=True, verbose_name='Cuotas cliente'),
        ),
    ]
