# Generated by Django 5.1.4 on 2025-02-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_bulk_sale_price_product_bulk_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('OPEN', 'Apertura Saco'), ('ADJ', 'Ajuste'), ('MERMA', 'Merma')], max_length=10, verbose_name='Tipo de movimiento'),
        ),
    ]
