# Generated by Django 5.1.4 on 2025-02-05 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_supplier_stockentry_stockentrydetail'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Proveedor'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
