# Generated by Django 5.1.4 on 2025-02-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_stockentry_supplier_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='changes_detail',
            field=models.JSONField(blank=True, help_text='Almacena los detalles de los cambios en formato JSON', null=True, verbose_name='Detalles de cambios'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('OPEN', 'Apertura Saco'), ('ADJ', 'Ajuste'), ('MERMA', 'Merma'), ('EDIT', 'Edición')], max_length=10, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='date',
            field=models.DateField(help_text='Fecha en formato YYYY-MM-DD', verbose_name='Fecha de ingreso'),
        ),
    ]
