# Generated by Django 5.1.4 on 2025-02-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productstock_changes_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Código único del producto', max_length=7, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Peso del saco en kilos', max_digits=6, verbose_name='Peso en kilos')),
                ('purchase_price', models.IntegerField(verbose_name='Precio de compra')),
                ('is_purchase_with_tax', models.BooleanField(default=True, verbose_name='Precio de compra incluye IVA')),
                ('sale_price', models.IntegerField(verbose_name='Precio de venta')),
                ('is_sale_with_tax', models.BooleanField(default=True, verbose_name='Precio de venta incluye IVA')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock en sacos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'ordering': ['weight'],
                'unique_together': {('product', 'weight')},
            },
        ),
        migrations.AddField(
            model_name='productstock',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Variante del producto (para movimientos de sacos)', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant', verbose_name='Variante'),
        ),
    ]
