# Generated by Django 5.1.4 on 2025-02-11 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_assign_skus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='is_bulk',
        ),
        migrations.AddField(
            model_name='product',
            name='is_bulk',
            field=models.BooleanField(default=False, help_text='Indica si este producto se vende a granel', verbose_name='Es producto a granel'),
        ),
        migrations.AddField(
            model_name='product',
            name='linked_products',
            field=models.ManyToManyField(blank=True, help_text='Productos que pueden abrirse para venta a granel', related_name='bulk_products', to='products.product', verbose_name='Productos vinculados'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='source_price',
            field=models.IntegerField(blank=True, help_text='Precio de compra del producto origen', null=True, verbose_name='Precio origen'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='source_product',
            field=models.ForeignKey(blank=True, help_text='Producto del cual proviene el movimiento (para aperturas de sacos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_movements', to='products.product', verbose_name='Producto origen'),
        ),
    ]
