# Generated by Django 5.1.4 on 2025-02-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productstock_is_bulk_product_is_bulk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='variant',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
