# Generated by Django 5.1.4 on 2025-02-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_productstock_variant_delete_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productstock',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('SALE', 'Venta'), ('PURCHASE', 'Compra'), ('INV', 'Inventario'), ('ADJ', 'Ajuste'), ('BULK', 'Apertura Granel')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('OPEN', 'Apertura Saco'), ('ADJ', 'Ajuste Inv'), ('MERMA', 'Merma'), ('EDIT', 'Edición')], max_length=10, verbose_name='Tipo de movimiento'),
        ),
    ]
